import fs from 'fs';

const path = './pessoas.txt';

const existe = fs.exists(path, (exists: boolean) => {
    if (exists) {
        fs.unlink(path, () => {
            console.log('Arquivo de pessoas apagado com sucesso!');
        });
    }
});

const pessoas = [
    {
        nome: 'Pietra Nair Rayssa Peixoto',
        sobrenome: '',
        idade: 26,
        cpf: '586.220.860-70',
        rg: '49.124.377-7',
        data_nasc: '23/10/1997',
        sexo: 'Feminino',
        signo: 'Escorpião',
        mae: 'Heloisa Eduarda Cláudia',
        pai: 'Gustavo Cauê Peixoto',
        email: 'pietra.nair.peixoto@outershoes.com.br',
        senha: 'HoirUMS6w4',
        cep: '65904-670',
        endereco: 'Rua Quatorze',
        numero: 488,
        bairro: 'Vila Macedo',
        cidade: 'Imperatriz',
        estado: 'MA',
        telefone_fixo: '(98) 2720-3847',
        celular: '(98) 98238-3451',
        altura: '1,82',
        peso: 64,
        tipo_sanguineo: 'A+',
        cor: 'roxo',
    },
    {
        nome: 'Amanda Alícia Antonella Mendes',
        sobrenome: '',
        idade: 75,
        cpf: '810.079.265-89',
        rg: '36.100.926-4',
        data_nasc: '06/05/1948',
        sexo: 'Feminino',
        signo: 'Touro',
        mae: 'Luana Lívia Allana',
        pai: 'Yago Thiago Ian Mendes',
        email: 'amanda_alicia_mendes@icloub.com',
        senha: 'CQL4BeDMe9',
        cep: '29206-360',
        endereco: 'Rua M 1 G',
        numero: 140,
        bairro: 'Nova Guarapari',
        cidade: 'Guarapari',
        estado: 'ES',
        telefone_fixo: '(27) 3575-4210',
        celular: '(27) 98360-1611',
        altura: '1,61',
        peso: 68,
        tipo_sanguineo: 'B+',
        cor: 'vermelho',
    },
    {
        nome: 'Filipe Oliver Barbosa',
        sobrenome: '',
        idade: 64,
        cpf: '203.193.797-95',
        rg: '26.563.330-8',
        data_nasc: '17/07/1959',
        sexo: 'Masculino',
        signo: 'Câncer',
        mae: 'Heloise Daiane',
        pai: 'Bruno Enzo Igor Barbosa',
        email: 'filipe_oliver_barbosa@cressem.com.br',
        senha: 'UONmKt58ZR',
        cep: '78052-110',
        endereco: 'Rua Chapada dos Guimarães',
        numero: 411,
        bairro: 'Doutor Fábio Leite',
        cidade: 'Cuiabá',
        estado: 'MT',
        telefone_fixo: '(65) 3853-0167',
        celular: '(65) 98662-1027',
        altura: '1,72',
        peso: 92,
        tipo_sanguineo: 'O+',
        cor: 'laranja',
    },
    {
        nome: 'Beatriz Heloise Aragão',
        sobrenome: '',
        idade: 21,
        cpf: '920.038.882-50',
        rg: '47.664.846-4',
        data_nasc: '24/03/2002',
        sexo: 'Feminino',
        signo: 'Áries',
        mae: 'Sônia Sophie Jennifer',
        pai: 'Bernardo Benício Erick Aragão',
        email: 'beatrizheloisearagao@edpbr.com.br',
        senha: 'lIEwY7uxYz',
        cep: '68950-970',
        endereco: 'Avenida Guarani 242',
        numero: 856,
        bairro: 'Centro',
        cidade: 'Amapá',
        estado: 'AP',
        telefone_fixo: '(96) 2534-0860',
        celular: '(96) 98721-3945',
        altura: '1,73',
        peso: 68,
        tipo_sanguineo: 'B+',
        cor: 'vermelho',
    },
    {
        nome: 'Ian Arthur Enrico de Paula',
        sobrenome: '',
        idade: 30,
        cpf: '853.479.739-00',
        rg: '27.338.296-2',
        data_nasc: '13/07/1993',
        sexo: 'Masculino',
        signo: 'Câncer',
        mae: 'Sophia Raquel',
        pai: 'Marcos Vinicius Benjamin Ian de Paula',
        email: 'ian-depaula71@ig.com',
        senha: '7yUzLhyDum',
        cep: '72833-511',
        endereco: 'Quadra Quadra 11',
        numero: 139,
        bairro: 'Parque Desportivo Brasília (Roosevelt)',
        cidade: 'Luziânia',
        estado: 'GO',
        telefone_fixo: '(61) 2518-9130',
        celular: '(61) 99387-3555',
        altura: '1,82',
        peso: 95,
        tipo_sanguineo: 'O-',
        cor: 'vermelho',
    },
    {
        nome: 'Levi Yago Gonçalves',
        sobrenome: '',
        idade: 43,
        cpf: '631.084.645-07',
        rg: '14.694.541-4',
        data_nasc: '07/02/1980',
        sexo: 'Masculino',
        signo: 'Aquário',
        mae: 'Tatiane Raquel',
        pai: 'Vinicius André Gonçalves',
        email: 'levi.yago.goncalves@jcoronel.com.br',
        senha: '0rnedCGUJq',
        cep: '77002-011',
        endereco: 'Quadra 405 Norte Alameda 13',
        numero: 820,
        bairro: 'Plano Diretor Norte',
        cidade: 'Palmas',
        estado: 'TO',
        telefone_fixo: '(63) 3519-0581',
        celular: '(63) 99898-3830',
        altura: '1,96',
        peso: 52,
        tipo_sanguineo: 'O+',
        cor: 'preto',
    },
    {
        nome: 'Bruno Bernardo Giovanni Moreira',
        sobrenome: '',
        idade: 53,
        cpf: '583.411.805-45',
        rg: '48.345.412-6',
        data_nasc: '21/05/1970',
        sexo: 'Masculino',
        signo: 'Gêmeos',
        mae: 'Carolina Tatiane Francisca',
        pai: 'Murilo Pedro Henrique Luiz Moreira',
        email: 'bruno_moreira@heinrich.com.br',
        senha: 'cKjHGMeCTQ',
        cep: '58028-360',
        endereco: 'Rua Sérgio Gomes Vieira',
        numero: 550,
        bairro: 'Ipês',
        cidade: 'João Pessoa',
        estado: 'PB',
        telefone_fixo: '(83) 3661-6377',
        celular: '(83) 98292-0144',
        altura: '1,62',
        peso: 57,
        tipo_sanguineo: 'A+',
        cor: 'amarelo',
    },
    {
        nome: 'Jorge Miguel Davi Galvão',
        sobrenome: '',
        idade: 30,
        cpf: '445.106.115-60',
        rg: '13.158.210-0',
        data_nasc: '11/08/1993',
        sexo: 'Masculino',
        signo: 'Leão',
        mae: 'Daniela Andreia',
        pai: 'Fernando Cauê Felipe Galvão',
        email: 'jorgemiguelgalvao@prlme.com.br',
        senha: 'BF5NlLB103',
        cep: '69093-607',
        endereco: 'Travessa Aripuanã',
        numero: 249,
        bairro: 'Colônia Terra Nova',
        cidade: 'Manaus',
        estado: 'AM',
        telefone_fixo: '(92) 3750-3531',
        celular: '(92) 98587-8533',
        altura: '1,62',
        peso: 53,
        tipo_sanguineo: 'B+',
        cor: 'vermelho',
    },
    {
        nome: 'Isabelle Marli Maitê Almeida',
        sobrenome: '',
        idade: 75,
        cpf: '338.184.226-99',
        rg: '44.554.502-1',
        data_nasc: '01/04/1948',
        sexo: 'Feminino',
        signo: 'Áries',
        mae: 'Vitória Julia Heloise',
        pai: 'Sebastião Tomás Oliver Almeida',
        email: 'isabellemarlialmeida@ericsson.com',
        senha: 'L5tgDQbAFa',
        cep: '58075-424',
        endereco: 'Rua Reginaldo Correia de Lima',
        numero: 667,
        bairro: 'Ernesto Geisel',
        cidade: 'João Pessoa',
        estado: 'PB',
        telefone_fixo: '(83) 2658-9124',
        celular: '(83) 99200-1989',
        altura: '1,69',
        peso: 54,
        tipo_sanguineo: 'B+',
        cor: 'vermelho',
    },
    {
        nome: 'Nelson Henry Lucca Oliveira',
        sobrenome: '',
        idade: 53,
        cpf: '993.352.892-05',
        rg: '14.692.173-2',
        data_nasc: '24/05/1970',
        sexo: 'Masculino',
        signo: 'Gêmeos',
        mae: 'Daniela Flávia',
        pai: 'Jorge Anthony Caio Oliveira',
        email: 'nelson_oliveira@dcabr.org.br',
        senha: 'emQhulPBgr',
        cep: '57955-970',
        endereco: 'Rua Luiz Holanda Cavalcante 61',
        numero: 705,
        bairro: 'Centro',
        cidade: 'Maragogi',
        estado: 'AL',
        telefone_fixo: '(82) 2524-7840',
        celular: '(82) 98737-6738',
        altura: '1,91',
        peso: 58,
        tipo_sanguineo: 'B+',
        cor: 'azul',
    },
    {
        nome: 'Daiane Elza Débora Monteiro',
        sobrenome: '',
        idade: 56,
        cpf: '127.154.611-60',
        rg: '34.970.888-5',
        data_nasc: '07/04/1967',
        sexo: 'Feminino',
        signo: 'Áries',
        mae: 'Joana Andrea',
        pai: 'Igor Caleb Monteiro',
        email: 'daianeelzamonteiro@umbernardo.com.br',
        senha: 'Z6UKTbnaf7',
        cep: '62050-400',
        endereco: 'Rua Vitória',
        numero: 172,
        bairro: 'Sinhá Sabóia',
        cidade: 'Sobral',
        estado: 'CE',
        telefone_fixo: '(88) 2903-5615',
        celular: '(88) 98812-3990',
        altura: '1,55',
        peso: 74,
        tipo_sanguineo: 'O-',
        cor: 'azul',
    },
    {
        nome: 'Gael Luís Campos',
        sobrenome: '',
        idade: 53,
        cpf: '451.133.790-00',
        rg: '44.470.399-8',
        data_nasc: '14/05/1970',
        sexo: 'Masculino',
        signo: 'Touro',
        mae: 'Juliana Louise',
        pai: 'Oliver Pietro Campos',
        email: 'gaelluiscampos@microlasersp.com.br',
        senha: 'op8TWb6f6M',
        cep: '59108-480',
        endereco: 'Rua Simone Banhos Teixeira',
        numero: 909,
        bairro: 'Potengi',
        cidade: 'Natal',
        estado: 'RN',
        telefone_fixo: '(84) 3930-4183',
        celular: '(84) 98489-7556',
        altura: '1,65',
        peso: 108,
        tipo_sanguineo: 'AB-',
        cor: 'azul',
    },
    {
        nome: 'Teresinha Daniela Sales',
        sobrenome: '',
        idade: 25,
        cpf: '255.599.807-14',
        rg: '38.232.201-0',
        data_nasc: '09/11/1998',
        sexo: 'Feminino',
        signo: 'Escorpião',
        mae: 'Manuela Giovana',
        pai: 'Miguel Benício Sales',
        email: 'teresinhadanielasales@embraer.com.br',
        senha: '5tUniQZyG1',
        cep: '89239-233',
        endereco: 'Rua Arno Krelling',
        numero: 330,
        bairro: 'Pirabeiraba (Pirabeiraba)',
        cidade: 'Joinville',
        estado: 'SC',
        telefone_fixo: '(47) 2649-5442',
        celular: '(47) 99724-3215',
        altura: '1,56',
        peso: 54,
        tipo_sanguineo: 'AB-',
        cor: 'preto',
    },
    {
        nome: 'Luana Sarah Costa',
        sobrenome: '',
        idade: 49,
        cpf: '987.821.402-86',
        rg: '30.034.542-2',
        data_nasc: '27/04/1974',
        sexo: 'Feminino',
        signo: 'Touro',
        mae: 'Julia Sueli Isabela',
        pai: 'Thomas Igor Raul Costa',
        email: 'luana_sarah_costa@oticascarol.com.br',
        senha: 'ZikMlysOFw',
        cep: '77828-548',
        endereco: 'Alameda das Bromélias',
        numero: 339,
        bairro: 'Loteamento Jardins Siena',

        cidade: 'Araguaína',
        estado: 'TO',
        telefone_fixo: '(63) 3817-5745',
        celular: '(63) 99910-5550',
        altura: '1,52',
        peso: 81,
        tipo_sanguineo: 'O+',
        cor: 'verde',
    },
    {
        nome: 'Ricardo Gabriel Elias Alves',
        sobrenome: '',
        idade: 39,
        cpf: '634.227.382-07',
        rg: '22.372.353-8',
        data_nasc: '24/10/1984',
        sexo: 'Masculino',
        signo: 'Escorpião',
        mae: 'Débora Rebeca',
        pai: 'Raul Hugo Alves',
        email: 'ricardo.gabriel.alves@senioraereo.com.br',
        senha: 'yZrHYf9USJ',
        cep: '24943-250',
        endereco: 'Rua Três',
        numero: 206,
        bairro: 'Inoã (Inoã)',
        cidade: 'Maricá',
        estado: 'RJ',
        telefone_fixo: '(21) 2995-9696',
        celular: '(21) 98228-4177',
        altura: '1,83',
        peso: 50,
        tipo_sanguineo: 'A-',
        cor: 'laranja',
    },
    {
        nome: 'Fábio Juan Pedro Santos',
        sobrenome: '',
        idade: 37,
        cpf: '011.446.518-59',
        rg: '12.598.577-0',
        data_nasc: '22/07/1986',
        sexo: 'Masculino',
        signo: 'Leão',
        mae: 'Sabrina Stefany Helena',
        pai: 'Davi Leonardo Santos',
        email: 'fabio.juan.santos@danielvasconcelos.com.br',
        senha: 'jlUbzauGYf',
        cep: '88658-971',
        endereco: 'Rua José Ozelame 172',
        numero: 280,
        bairro: 'Centro',
        cidade: 'Rio Rufino',
        estado: 'SC',
        telefone_fixo: '(49) 3915-6525',
        celular: '(49) 99669-8150',
        altura: '1,74',
        peso: 92,
        tipo_sanguineo: 'AB+',
        cor: 'preto',
    },
    {
        nome: 'Priscila Alessandra da Conceição',
        sobrenome: '',
        idade: 45,
        cpf: '253.454.354-72',
        rg: '44.066.678-8',
        data_nasc: '22/05/1978',
        sexo: 'Feminino',
        signo: 'Gêmeos',
        mae: 'Marina Ester',
        pai: 'Matheus Gael Erick da Conceição',
        email: 'priscila.alessandra.daconceicao@p4ed.com',
        senha: 'GSuMT5HBOY',
        cep: '77016-128',
        endereco: 'Quadra 505 Sul Avenida NS 7',
        numero: 530,
        bairro: 'Plano Diretor Sul',
        cidade: 'Palmas',
        estado: 'TO',
        telefone_fixo: '(63) 3551-3033',
        celular: '(63) 99324-2827',
        altura: '1,70',
        peso: 67,
        tipo_sanguineo: 'O+',
        cor: 'preto',
    },
    {
        nome: 'Aurora Caroline Renata Ferreira',
        sobrenome: '',
        idade: 70,
        cpf: '591.058.607-68',
        rg: '25.033.960-2',
        data_nasc: '02/06/1953',
        sexo: 'Feminino',
        signo: 'Gêmeos',
        mae: 'Isadora Emilly Amanda',
        pai: 'Julio Felipe Ferreira',
        email: 'aurora_ferreira@flextroniocs.copm.br',
        senha: 'QGUX5sNAH7',
        cep: '69918-188',
        endereco: 'Rua Fontenele de Castro',
        numero: 365,
        bairro: 'Estação Experimental',
        cidade: 'Rio Branco',
        estado: 'AC',
        telefone_fixo: '(68) 2522-4791',
        celular: '(68) 99667-5599',
        altura: '1,85',
        peso: 70,
        tipo_sanguineo: 'A+',
        cor: 'laranja',
    },
    {
        nome: 'Helena Maitê da Silva',
        sobrenome: '',
        idade: 19,
        cpf: '241.273.244-22',
        rg: '44.854.746-6',
        data_nasc: '13/11/2004',
        sexo: 'Feminino',
        signo: 'Escorpião',
        mae: 'Isis Luzia Clara',
        pai: 'Vicente Pedro da Silva',
        email: 'helena_maite_dasilva@cantinadafazenda.com.br',
        senha: 'Kl5gaDfxLw',
        cep: '64059-220',
        endereco: 'Rua Penópolis',
        numero: 158,
        bairro: 'Satélite',
        cidade: 'Teresina',
        estado: 'PI',
        telefone_fixo: '(86) 3674-9304',
        celular: '(86) 99789-0417',
        altura: '1,70',
        peso: 64,
        tipo_sanguineo: 'AB+',
        cor: 'verde',
    },
    {
        nome: 'Rafael Mário Novaes',
        sobrenome: '',
        idade: 70,
        cpf: '527.667.834-07',
        rg: '29.420.789-2',
        data_nasc: '01/10/1953',
        sexo: 'Masculino',
        signo: 'Libra',
        mae: 'Isabelly Valentina Ana',
        pai: 'Osvaldo Daniel Novaes',
        email: 'rafaelmarionovaes@gastrolight.com.br',
        senha: 'JCAJdFMa4U',
        cep: '31150-670',
        endereco: 'Rua Haydée Bambirra',
        numero: 495,
        bairro: 'Santa Cruz',
        cidade: 'Belo Horizonte',
        estado: 'MG',
        telefone_fixo: '(31) 3860-5392',
        celular: '(31) 98807-1485',
        altura: '1,61',
        peso: 64,
        tipo_sanguineo: 'AB+',
        cor: 'amarelo',
    },
    {
        nome: 'Débora Lorena da Rosa',
        sobrenome: '',
        idade: 80,
        cpf: '560.716.276-13',
        rg: '46.590.891-3',
        data_nasc: '10/03/1943',
        sexo: 'Feminino',
        signo: 'Peixes',
        mae: 'Vitória Isadora',
        pai: 'Vinicius Elias Osvaldo da Rosa',
        email: 'deboralorenadarosa@telecall.com',
        senha: 'U9c0rrQweS',
        cep: '58700-050',
        endereco: 'Rua Doutor José Genuíno',
        numero: 951,
        bairro: 'Centro',
        cidade: 'Patos',
        estado: 'PB',
        telefone_fixo: '(83) 3670-7392',
        celular: '(83) 99509-2431',
        altura: '1,76',
        peso: 72,
        tipo_sanguineo: 'B+',
        cor: 'vermelho',
    },
    {
        nome: 'Giovanna Antônia Kamilly Figueiredo',
        sobrenome: '',
        idade: 28,
        cpf: '106.995.491-83',
        rg: '12.055.167-6',
        data_nasc: '12/03/1995',
        sexo: 'Feminino',
        signo: 'Peixes',
        mae: 'Fátima Aline Sueli',
        pai: 'Filipe Edson Figueiredo',
        email: 'giovannaantoniafigueiredo@yahoo.com .br',
        senha: 'yaEMWoShe7',
        cep: '88168-114',
        endereco: 'Rua das Margaridas',
        numero: 126,
        bairro: 'São Miguel (Guaporanga)',
        cidade: 'Biguaçu',
        estado: 'SC',
        telefone_fixo: '(48) 2691-9871',
        celular: '(48) 99364-9314',
        altura: '1,75',
        peso: 80,
        tipo_sanguineo: 'O-',
        cor: 'preto',
    },
    {
        nome: 'Cláudio Osvaldo Rodrigues',
        sobrenome: '',
        idade: 52,
        cpf: '066.460.071-95',
        rg: '13.831.756-2',
        data_nasc: '15/01/1971',
        sexo: 'Masculino',
        signo: 'Capricórnio',
        mae: 'Priscila Juliana',
        pai: 'Kaique Benedito Rodrigues',
        email: 'claudio-rodrigues81@andrediaz.com',
        senha: 'fymek8eLft',
        cep: '20720-030',
        endereco: 'Rua Piranga',
        numero: 316,
        bairro: 'Méier',
        cidade: 'Rio de Janeiro',
        estado: 'RJ',
        telefone_fixo: '(21) 2616-4296',
        celular: '(21) 99692-1002',
        altura: '1,66',
        peso: 97,
        tipo_sanguineo: 'A-',
        cor: 'azul',
    },
    {
        nome: 'Elias Antonio César Melo',
        sobrenome: '',
        idade: 50,
        cpf: '772.741.974-52',
        rg: '32.579.163-6',
        data_nasc: '07/05/1973',
        sexo: 'Masculino',
        signo: 'Touro',
        mae: 'Teresinha Mirella',
        pai: 'Murilo Pedro Vicente Melo',
        email: 'eliasantoniomelo@transporteveloz.com.br',
        senha: 'RPYFzDO26J',
        cep: '77813-755',
        endereco: 'Rua E',
        numero: 572,
        bairro: 'Vila Aliança',
        cidade: 'Araguaína',
        estado: 'TO',
        telefone_fixo: '(63) 2779-8249',
        celular: '(63) 98362-6385',
        altura: '1,85',
        peso: 66,
        tipo_sanguineo: 'O-',
        cor: 'vermelho',
    },
    {
        nome: 'Kaique Fábio Araújo',
        sobrenome: '',
        idade: 24,
        cpf: '540.449.605-34',
        rg: '44.885.866-6',
        data_nasc: '27/07/1999',
        sexo: 'Masculino',
        signo: 'Leão',
        mae: 'Sara Stella',
        pai: 'César Emanuel Alexandre Araújo',
        email: 'kaique.fabio.araujo@quintadoslagos.com.br',
        senha: '2n6QU1e4Cz',
        cep: '78052-568',
        endereco: 'Rua Z',
        numero: 191,
        bairro: 'Jardim Brasil',
        cidade: 'Cuiabá',
        estado: 'MT',
        telefone_fixo: '(65) 3947-1503',
        celular: '(65) 98203-4979',
        altura: '1,79',
        peso: 50,
        tipo_sanguineo: 'AB-',
        cor: 'roxo',
    },
    {
        nome: 'Stella Emily Lima',
        sobrenome: '',
        idade: 69,
        cpf: '160.316.993-89',
        rg: '30.908.592-5',
        data_nasc: '07/07/1954',
        sexo: 'Feminino',
        signo: 'Câncer',
        mae: 'Antonella Andrea Stefany',
        pai: 'Thales Thomas Lima',
        email: 'stella-lima87@w3ag.com',
        senha: 'aJ5yXuAUTz',
        cep: '72915-558',
        endereco: 'Quadra QA 27',
        numero: 251,
        bairro: 'Mansões Olinda',
        cidade: 'Águas Lindas de Goiás',
        estado: 'GO',
        telefone_fixo: '(61) 2617-4581',
        celular: '(61) 98663-8053',
        altura: '1,63',
        peso: 74,
        tipo_sanguineo: 'B+',
        cor: 'vermelho',
    },
    {
        nome: 'Vicente Luan Gael Castro',
        sobrenome: '',
        idade: 50,
        cpf: '511.214.952-30',
        rg: '48.346.959-2',
        data_nasc: '01/08/1973',
        sexo: 'Masculino',
        signo: 'Leão',
        mae: 'Marli Mirella Giovana',
        pai: 'Ryan Cláudio Castro',
        email: 'vicente_luan_castro@fabiooliva.com.br',
        senha: '0AyoyAOKpa',
        cep: '57305-315',
        endereco: 'Rua São Tomé',
        numero: 238,
        bairro: 'Manoel Teles',
        cidade: 'Arapiraca',
        estado: 'AL',
        telefone_fixo: '(82) 2508-4380',
        celular: '(82) 98316-7942',
        altura: '1,98',
        peso: 100,
        tipo_sanguineo: 'B-',
        cor: 'vermelho',
    },
    {
        nome: 'Ester Emilly Silveira',
        sobrenome: '',
        idade: 78,
        cpf: '332.850.646-25',
        rg: '10.948.386-8',
        data_nasc: '26/06/1945',
        sexo: 'Feminino',
        signo: 'Câncer',
        mae: 'Emily Luana',
        pai: 'Yago Matheus Silveira',
        email: 'ester_emilly_silveira@startingfitness.com.br',
        senha: 'SzreIurxrw',
        cep: '69918-248',
        endereco: 'Travessa Jaguari',
        numero: 625,
        bairro: 'Isaura Parente',
        cidade: 'Rio Branco',
        estado: 'AC',
        telefone_fixo: '(68) 3610-5311',
        celular: '(68) 99436-3253',
        altura: '1,71',
        peso: 61,
        tipo_sanguineo: 'AB-',
        cor: 'roxo',
    },
    {
        nome: 'Giovanni Nathan Martins',
        sobrenome: '',
        idade: 27,
        cpf: '677.770.444-27',
        rg: '25.511.875-2',
        data_nasc: '14/05/1996',
        sexo: 'Masculino',
        signo: 'Touro',
        mae: 'Renata Bianca Vitória',
        pai: 'Theo Iago Thomas Martins',
        email: 'giovanni_nathan_martins@anfip.org.br',
        senha: 'PIrzRaTl57',
        cep: '81330-202',
        endereco: 'Travessa Dina Ramos Breyer',
        numero: 301,
        bairro: 'Fazendinha',
        cidade: 'Curitiba',
        estado: 'PR',
        telefone_fixo: '(41) 2945-2448',
        celular: '(41) 99651-9125',
        altura: '1,60',
        peso: 75,
        tipo_sanguineo: 'O+',
        cor: 'vermelho',
    },
    {
        nome: 'Fabiana Laura Sabrina Teixeira',
        sobrenome: '',
        idade: 23,
        cpf: '672.147.878-14',
        rg: '21.330.245-7',
        data_nasc: '16/04/2000',
        sexo: 'Feminino',
        signo: 'Áries',
        mae: 'Fabiana Raquel Camila',
        pai: 'Kaique Cláudio Teixeira',
        email: 'fabiana.laura.teixeira@yhaoo.com.br',
        senha: 'fOHhOqFEgE',
        cep: '65090-581',
        endereco: 'Travessa Ademar de Barros',
        numero: 574,
        bairro: 'Nova República',
        cidade: 'São Luís',
        estado: 'MA',
        telefone_fixo: '(98) 2884-0716',
        celular: '(98) 99912-3649',
        altura: '1,61',
        peso: 80,
        tipo_sanguineo: 'AB-',
        cor: 'vermelho',
    },
];

pessoas.forEach((pessoa) => {
    const nomeCompleto = pessoa.nome;
    const partesNome = nomeCompleto.split(' ');
    const nome = partesNome[0];
    const sobrenome = partesNome.slice(1).join(' ');

    pessoa.nome = nome;
    pessoa.sobrenome = sobrenome;

    const linha = `'${nome}, ${sobrenome}, ${pessoa.email}, ${pessoa.cidade}',\n`;

    fs.appendFile(path, linha, (err) => {
        if (err) {
            console.error(err);
        }
    });
});
console.log('Arquivo de pessoas salvo com sucesso!');


// const pessoasList = [
//     'Abaíra, São Paulo, davidsonc@gmail.com, 797444195-04',
//     'Abaré, São Paulo, davidsonc@gmail.com, 797444195-04',
//     'Acajutiba, São Paulo, davidsonc@gmail.com, 797444195-04',
//     'Adustina, São Paulo, davidsonc@gmail.com, 797444195-04',
//     'Água Fria, São Paulo, davidsonc@gmail.com, 797444195-04',
// ];

// const objetoPessoas = pessoasList.map((pessoa) => {
//     const match = pessoa.match(/^(.*),\s*(.*),\s*(.*),\s*(.*)$/);
//     if (match) {
//         const [_, nome, sobrenome, email, cidadeId] = match;
//         return { nome, sobrenome, email, cidadeId };
//     }
//     throw new Error();
// });
// console.log(objetoPessoas);

// const lista: string[] = [
//     'brotas, Bahia, 44545454',
//     'brejinhos, Pernambuco, 21544564561541',
// ];
// const regex: RegExp = /^(.*),\s*(.*),\s*(\d+)$/;

// lista.forEach((item: string) => {
//     const matches: RegExpMatchArray | null = item.match(regex);
//     if (matches) {
//         const nome: string = matches[1];
//         const estado: string = matches[2];
//         const cep: string = matches[3];

//         console.log('Nome:', nome);
//         console.log('Estado:', estado);
//         console.log('CEP:', cep);
//     }
// });
