name: Azure CI

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: SSH into Azure VM and git pull
              run: |
                  touch id_rsa
                  chmod 600 id_rsa
                  echo "${{ secrets.AZURE_KEY }}" > id_rsa
                  ssh -i id_rsa -o StrictHostKeyChecking=no azureuser@172.174.217.62 'cd /home/azureuser/api && git pull && pm2 restart 0'
